// AUTO-GENERATED - DO NOT EDIT.
// Generated by tools/generate-ui-dts.mjs

export {};

declare global {
  namespace UI {
    function AppShell(...args: any[]): HTMLElement;

    function Avatar(...args: any[]): HTMLElement;

    function Badge(...args: any[]): HTMLElement;

    function Banner(...args: any[]): HTMLElement;

    function Breadcrumbs(...args: any[]): HTMLElement;

    function Btn(...args: any[]): HTMLElement;

    function Card(...args: any[]): HTMLElement;

    function CardBody(...args: any[]): HTMLElement;

    function CardFooter(...args: any[]): HTMLElement;

    function CardHeader(...args: any[]): HTMLElement;

    function Checkbox(...args: any[]): HTMLElement;

    function Chip(...args: any[]): HTMLElement;

    function Col(...args: any[]): HTMLElement;

    function Container(...args: any[]): HTMLElement;

    function ContextMenu(props?: Record<string, any>): HTMLElement | DocumentFragment | any;

    function Date(...args: any[]): HTMLElement;

    function Dialog(...args: any[]): HTMLElement | DocumentFragment | any;

    function Drawer(...args: any[]): HTMLElement | DocumentFragment | any;

    function Footer(...args: any[]): HTMLElement;

    function Form(...args: any[]): HTMLElement;

    function FormField(props?: Record<string, any>): HTMLElement;

    function Grid(...args: any[]): HTMLElement;

    function GridCol(...args: any[]): HTMLElement;

    function Header(...args: any[]): HTMLElement;

    function Icon(...args: any[]): HTMLElement;

    function Input(props?: Record<string, any>): HTMLElement;

    function InputRaw(props?: Record<string, any>): HTMLElement;

    function Item(...args: any[]): HTMLElement;

    function Layout(props?: {
        aside?: any;
        class?: string | string[] | null | undefined;
        drawerBreakpoint?: number;
        drawerOpen?: any;
        drawerWidth?: number;
        escClose?: boolean;
        footer?: any;
        header?: any;
        noDrawer?: boolean;
        overlayClose?: boolean;
        page?: any;
        slots?: any;
        stickyAside?: boolean;
        stickyFooter?: boolean;
        stickyHeader?: boolean;
        tagPage?: boolean;
      }
    ): HTMLElement;

    function List(...args: any[]): HTMLElement | DocumentFragment | any;

    function LoadingBar(...args: any[]): HTMLElement | DocumentFragment | any;

    function Menu(props?: Record<string, any>): HTMLElement | DocumentFragment | any;

    function Notify(props?: Record<string, any>): HTMLElement | DocumentFragment | any;

    function Page(...args: any[]): HTMLElement;

    function Pagination(...args: any[]): HTMLElement;

    function Parallax(...args: any[]): HTMLElement;

    function Popover(props?: Record<string, any>): HTMLElement | DocumentFragment | any;

    function Progress(...args: any[]): HTMLElement;

    function Radio(...args: any[]): HTMLElement;

    function Rating(...args: any[]): HTMLElement;

    function RouteTab(...args: any[]): HTMLElement;

    function Row(...args: any[]): HTMLElement;

    function Select(props?: Record<string, any>): HTMLElement | DocumentFragment | any;

    function Separator(...args: any[]): HTMLElement;

    function Slider(...args: any[]): HTMLElement;

    function Spacer(...args: any[]): HTMLElement;

    function Spinner(...args: any[]): HTMLElement;

    function Table(...args: any[]): HTMLElement;

    function Tabs(...args: any[]): HTMLElement | DocumentFragment | any;

    function Time(...args: any[]): HTMLElement;

    function Toggle(...args: any[]): HTMLElement;

    function Toolbar(...args: any[]): HTMLElement;

    function Tooltip(...args: any[]): HTMLElement | DocumentFragment | any;
  }
  namespace CMSwift {
    function Can(...args: any[]): any;

    function component(...args: any[]): any;

    function enableAutoCleanup(): any;

    function isDev(): any;

    function mount(...args: any[]): any;

    function omit(...args: any[]): any;

    function ready(...args: any[]): any;

    function rodBind(...args: any[]): any;

    function rodFromSignal(...args: any[]): any;

    function rodModel(...args: any[]): any;

    function signalModel(...args: any[]): any;

    function uiNormalizeArgs(...args: any[]): any;

    function use(...args: any[]): any;

    function useForm(props?: Record<string, any>): any;

    function useRoute(...args: any[]): any;

    function useRouter(...args: any[]): any;

    function useStore(...args: any[]): any;

    namespace http {
      function del(...args: any[]): any;

      function delJSON(...args: any[]): any;

      function get(...args: any[]): any;

      function getJSON(...args: any[]): any;

      function onAfter(...args: any[]): any;

      function onBefore(...args: any[]): any;

      function onError(...args: any[]): any;

      function patch(...args: any[]): any;

      function patchJSON(...args: any[]): any;

      function post(...args: any[]): any;

      function postJSON(...args: any[]): any;

      function put(...args: any[]): any;

      function putJSON(...args: any[]): any;

      function request(): any;

      function state(): any;
    }
  }
}
