import { header } from "./header.cms";
const coseBasic = _rod("cms-d-none");

setTimeout(() => {
  coseBasic.value = "";
}, 100);

const chip = _h.div({ class: "cms-panel cms-page" },
  _h.h1("Chip"),
  _h.p("Chip compatto con icona e label, opzionale rimozione. Varianti dense/outline e slot per icon/label."),
  _h.h2("Props principali"),
  _ui.List(
    _ui.Item("size: dimensione del componente (xs-sm-md-lg-xl)"),
    _ui.Item("state: success, warning, danger, info, primary, secondary"),
    _ui.Item("outline, shadow, borderRadius, clickable per stile e interazione")
  ),
  _h.h2("Esempio completo"),
  _ui.Card({
    gradient: true, identifier: "Basic",
    header: [
      _ui.Spacer(),
      _ui.Btn({ icon: "code", class: "cms-m-l-auto", dense: true }),
      _ui.Btn({ icon: "#brand-github", class: "cms-m-l-auto", dense: true }),
      _ui.Btn({ icon: "#brand-codepen", class: "cms-m-l-auto", dense: true }),
    ]


  },
    _ui.Row(
      _ui.Col(
        _ui.Chip("None"),
        _ui.Chip({ color: "success" }, "Success"),
        _ui.Chip({ color: "warning" }, "Warning"),
        _ui.Chip({ color: "danger" }, "Danger"),
        _ui.Chip({ color: "info" }, "Info"),
        _ui.Chip({ color: "primary" }, "Primary"),
        _ui.Chip({ color: "secondary" }, "Secondary"),
        _ui.Chip({ color: "dark", }, "Dark"),
        _ui.Chip({ color: "light" }, "Light"),
      ),
      _ui.Col({ col: 12, class: coseBasic },
        _ui.Chip("None"),
        _ui.Chip({ color: "success" }, "Success"),
        _ui.Chip({ color: "warning" }, "Warning"),
        _ui.Chip({ color: "danger" }, "Danger"),
        _ui.Chip({ color: "info" }, "Info"),
        _ui.Chip({ color: "primary" }, "Primary"),
        _ui.Chip({ color: "secondary" }, "Secondary"),
        _ui.Chip({ color: "dark", }, "Dark"),
        _ui.Chip({ color: "light" }, "Light"),
      )
    )
  ),
  _ui.Card({ header: "Size", class: "cms-m-t-sm" },
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, color: "success", size: "xxs" }, "Success xxs"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, color: "success", size: "xs" }, "Success xs"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, color: "warning", size: "sm" }, "Warning sm"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, color: "danger", size: "md" }, "Danger md"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, color: "info", size: "lg" }, "Info lg"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, color: "primary", size: "xl" }, "Primary xl"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, color: "secondary", size: "xxl" }, "Secondary xxl"),
  ),
  _ui.Card({ header: "Shadow", class: "cms-m-t-sm" },
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, shadow: true }, "None"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, shadow: true, color: "success" }, "Success"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, shadow: true, color: "warning" }, "Warning"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, shadow: true, color: "danger" }, "Danger"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, shadow: true, color: "info" }, "Info"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, shadow: true, color: "primary" }, "Primary"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, shadow: true, color: "secondary" }, "Secondary"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, shadow: true, color: "dark", }, "Dark"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, shadow: true, color: "light" }, "Light"),
  ),
  _ui.Card({ header: "Light shadow", class: "cms-m-t-sm" },
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, lightShadow: true }, "None"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, lightShadow: true, color: "success" }, "Success"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, lightShadow: true, color: "warning" }, "Warning"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, lightShadow: true, color: "danger" }, "Danger"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, lightShadow: true, color: "info" }, "Info"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, lightShadow: true, color: "primary" }, "Primary"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, lightShadow: true, color: "secondary" }, "Secondary"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, lightShadow: true, color: "dark", }, "Dark"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, lightShadow: true, color: "light" }, "Light"),
  ),
  _ui.Card({ header: "Border", class: "cms-m-t-sm" },
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, border: true }, "None"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, border: true, color: "success" }, "Success"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, border: true, color: "warning" }, "Warning"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, border: true, color: "danger" }, "Danger"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, border: true, color: "info" }, "Info"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, border: true, color: "primary" }, "Primary"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, border: true, color: "secondary" }, "Secondary"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, border: true, color: "dark", }, "Dark"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, border: true, color: "light" }, "Light"),
  ),
  _ui.Card({ header: "Glossy", class: "cms-m-t-sm" },
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, glossy: true }, "None"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, clickable: true, glossy: true, color: "success" }, "Success"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, glossy: true, color: "warning" }, "Warning"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, glossy: true, color: "danger" }, "Danger"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, glossy: true, color: "info" }, "Info"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, glossy: true, color: "primary" }, "Primary"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, glossy: true, color: "secondary" }, "Secondary"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, glossy: true, color: "dark", }, "Dark"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, glossy: true, color: "light" }, "Light"),
  ),
  _ui.Card({ header: "Glossy + border", class: "cms-m-t-sm" },
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, border: true, glossy: true }, "None"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, border: true, clickable: true, glossy: true, color: "success" }, "Success"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, border: true, glossy: true, color: "warning" }, "Warning"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, border: true, glossy: true, color: "danger" }, "Danger"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, border: true, glossy: true, color: "info" }, "Info"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, border: true, glossy: true, color: "primary" }, "Primary"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, border: true, glossy: true, color: "secondary" }, "Secondary"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, border: true, glossy: true, color: "dark", }, "Dark"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, border: true, glossy: true, color: "light" }, "Light"),
  ),
  _ui.Card({ header: "Glow", class: "cms-m-t-sm" },
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, glow: true }, "None"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, glow: true, color: "success" }, "Success"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, glow: true, color: "warning" }, "Warning"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, glow: true, color: "danger" }, "Danger"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, glow: true, color: "info" }, "Info"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, glow: true, color: "primary" }, "Primary"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, glow: true, color: "secondary" }, "Secondary"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, glow: true, color: "dark", }, "Dark"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, glow: true, color: "light" }, "Light"),
  ),
  _ui.Card({
    header: "Glass",
    class: "cms-m-t-sm"
  },
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, glass: true }, "None"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, glass: true, color: "success" }, "Success"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, glass: true, color: "warning" }, "Warning"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, glass: true, color: "danger" }, "Danger"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, glass: true, color: "info" }, "Info"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, glass: true, color: "primary" }, "Primary"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, glass: true, color: "secondary" }, "Secondary"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, glass: true, color: "dark", }, "Dark"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, glass: true, color: "light" }, "Light"),
  ),
  _ui.Card({
    header: "Gradient",
    class: "cms-m-t-sm"
  },
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, gradient: true }, "None"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, gradient: true, color: "success" }, "Success"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, gradient: true, color: "warning" }, "Warning"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, gradient: true, color: "danger" }, "Danger"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, gradient: true, color: "info" }, "Info"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, gradient: true, color: "primary" }, "Primary"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, gradient: true, color: "secondary" }, "Secondary"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, gradient: true, color: "dark", }, "Dark"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, gradient: true, color: "light" }, "Light"),
  ),
  _ui.Card({ header: "Outline", class: "cms-m-t-sm" },
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, outline: true }, "None"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, outline: true, color: "success" }, "Success"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, outline: true, color: "warning" }, "Warning"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, outline: true, color: "danger" }, "Danger"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, outline: true, color: "info" }, "Info"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, outline: true, color: "primary" }, "Primary"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, outline: true, color: "secondary" }, "Secondary"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, outline: true, color: "dark", }, "Dark"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, outline: true, color: "light" }, "Light"),
  ),
  _ui.Card({ header: "Outline + Glow", class: "cms-m-t-sm" },
    _ui.Chip({ icon: "token", iconRight: "home", glow: true, removable: true, clickable: true, outline: true }, "None"),
    _ui.Chip({ icon: "token", iconRight: "home", glow: true, removable: true, clickable: true, outline: true, color: "success" }, "Success"),
    _ui.Chip({ icon: "token", iconRight: "home", glow: true, removable: true, clickable: true, outline: true, color: "warning" }, "Warning"),
    _ui.Chip({ icon: "token", iconRight: "home", glow: true, removable: true, clickable: true, outline: true, color: "danger" }, "Danger"),
    _ui.Chip({ icon: "token", iconRight: "home", glow: true, removable: true, clickable: true, outline: true, color: "info" }, "Info"),
    _ui.Chip({ icon: "token", iconRight: "home", glow: true, removable: true, clickable: true, outline: true, color: "primary" }, "Primary"),
    _ui.Chip({ icon: "token", iconRight: "home", glow: true, removable: true, clickable: true, outline: true, color: "secondary" }, "Secondary"),
    _ui.Chip({ icon: "token", iconRight: "home", glow: true, removable: true, clickable: true, outline: true, color: "dark", }, "Dark"),
    _ui.Chip({ icon: "token", iconRight: "home", glow: true, removable: true, clickable: true, outline: true, color: "light" }, "Light"),
  ),
  _ui.Card({ header: "Outline + Glossy", class: "cms-m-t-sm" },
    _ui.Chip({ icon: "token", iconRight: "home", glossy: true, removable: true, clickable: true, outline: true }, "None"),
    _ui.Chip({ icon: "token", iconRight: "home", glossy: true, removable: true, clickable: true, outline: true, color: "success" }, "Success"),
    _ui.Chip({ icon: "token", iconRight: "home", glossy: true, removable: true, clickable: true, outline: true, color: "warning" }, "Warning"),
    _ui.Chip({ icon: "token", iconRight: "home", glossy: true, removable: true, clickable: true, outline: true, color: "danger" }, "Danger"),
    _ui.Chip({ icon: "token", iconRight: "home", glossy: true, removable: true, clickable: true, outline: true, color: "info" }, "Info"),
    _ui.Chip({ icon: "token", iconRight: "home", glossy: true, removable: true, clickable: true, outline: true, color: "primary" }, "Primary"),
    _ui.Chip({ icon: "token", iconRight: "home", glossy: true, removable: true, clickable: true, outline: true, color: "secondary" }, "Secondary"),
    _ui.Chip({ icon: "token", iconRight: "home", glossy: true, removable: true, clickable: true, outline: true, color: "dark", }, "Dark"),
    _ui.Chip({ icon: "token", iconRight: "home", glossy: true, removable: true, clickable: true, outline: true, color: "light" }, "Light"),
  ),
  _ui.Card({ header: "Outline + Glass", class: "cms-m-t-sm" },
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, outline: true, glass: true }, "None"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, outline: true, glass: true, color: "success" }, "Success"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, outline: true, glass: true, color: "warning" }, "Warning"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, outline: true, glass: true, color: "danger" }, "Danger"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, outline: true, glass: true, color: "info" }, "Info"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, outline: true, glass: true, color: "primary" }, "Primary"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, outline: true, glass: true, color: "secondary" }, "Secondary"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, outline: true, glass: true, color: "dark", }, "Dark"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, outline: true, glass: true, color: "light" }, "Light"),
  ),
  _ui.Card({ header: "Outline + Light Shadow", class: "cms-m-t-sm" },
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, lightShadow: true, outline: true }, "None"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, lightShadow: true, outline: true, color: "success" }, "Success"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, lightShadow: true, outline: true, color: "warning" }, "Warning"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, lightShadow: true, outline: true, color: "danger" }, "Danger"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, lightShadow: true, outline: true, color: "info" }, "Info"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, lightShadow: true, outline: true, color: "primary" }, "Primary"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, lightShadow: true, outline: true, color: "secondary" }, "Secondary"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, lightShadow: true, outline: true, color: "dark", }, "Dark"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, lightShadow: true, outline: true, color: "light" }, "Light"),
  ),
  _ui.Card({ header: "Text Gradient", class: "cms-m-t-sm" },
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, textGradient: true, }, "None"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, textGradient: true, color: "success" }, "Success"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, textGradient: true, color: "warning" }, "Warning"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, textGradient: true, color: "danger" }, "Danger"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, textGradient: true, color: "info" }, "Info"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, textGradient: true, color: "primary" }, "Primary"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, textGradient: true, color: "secondary" }, "Secondary"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, textGradient: true, color: "dark", }, "Dark"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, textGradient: true, color: "light" }, "Light"),
  ),
  _ui.Card({ header: "Outline + Text Gradient", class: "cms-m-t-sm" },
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, textGradient: true, outline: true }, "None"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, textGradient: true, outline: true, color: "success" }, "Success"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, textGradient: true, outline: true, color: "warning" }, "Warning"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, textGradient: true, outline: true, color: "danger" }, "Danger"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, textGradient: true, outline: true, color: "info" }, "Info"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, textGradient: true, outline: true, color: "primary" }, "Primary"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, textGradient: true, outline: true, color: "secondary" }, "Secondary"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, textGradient: true, outline: true, color: "dark", }, "Dark"),
    _ui.Chip({ icon: "token", iconRight: "home", removable: true, clickable: true, textGradient: true, outline: true, color: "light" }, "Light"),
  ),
  _h.h2("Documentazione API"),
  CMSwift.ui.DocTable("Chip")
);

export { chip };